import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import {NuqsAdapter} from "nuqs/adapters/next/app";
import RegisterDialog from "@/components/auth/RegisterDialog";
import LoginDialog from "@/components/auth/LoginDialog";
import QueryProvider from "@/context/query-provider";
import { Suspense } from "react";
import FallbackLoader from "@/components/FallbackLoader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Community Shop",
  description: "Generated by create next",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#EBF2F7] tialiased`}>
        <QueryProvider>
          <Suspense fallback={<FallbackLoader />}></Suspense>
          <NuqsAdapter>
          <RegisterDialog/>
          <LoginDialog/>
          {children}
          </NuqsAdapter>
          <Toaster/>
        </QueryProvider>
      </body>
    </html>
  );
}
